<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Form $block */
?>
<div class="block review-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Comment')) ?></strong></div>
    <div class="block-content">

        <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form"
              data-role="product-review-form" data-bind="scope: 'review-form'">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_fields_before') ?>
            <fieldset class="fieldset review-fieldset"
                      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <legend class="legend review-legend">
                    <span><?= $block->escapeHtml(__("You're commenting:")) ?></span><strong><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></strong>
                </legend>
                <br/>

                <div class="field review-field-nickname required">
                    <label for="nickname_field"
                           class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input type="text" name="email" id="nickname_field" class="input-email"
                               data-validate="{required:true}" data-bind="value: email()"/>
                    </div>
                </div>
                <div class="field review-field-text required">
                    <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment_field" cols="5" rows="3" data-validate="{required:true}"></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar review-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Submit Comment')) ?></span></button>
                </div>
            </div>
        </form>

    </div>
</div>
