<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Form $block */
?>
<?php // Get current product
$product = $block->getProduct();
?>

<div class="block review-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
    <div class="block-content">

            <form action="<?= $this->getUrl("productcomment/index/save/")  ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="product_id" id="product_id" value="<?= $product->getId() ?> " />
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <legend class="legend review-legend"><span><?= $block->escapeHtml(__("You're comment:")) ?></span></legend><br />

                    <div class="field review-field-nickname required">
                        <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input type="text" name="customer_email" id="customer_email_field" class="input-text" data-validate="{required:true}" data-bind="value: customer_email()" />
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Write your comment')) ?></span></label>
                        <div class="control">
                            <textarea name="customer_comment" id="customer_comment_field" cols="5" rows="3" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Your Comment')) ?></span></button>
                    </div>
                </div>
            </form>
    </div>
</div>
